### ISSUE TITLE
Bot stopped working?

### ISSUE THREAD

**Issue by CodedbyRed** [seveneightn9ne/keybase-reminder-bot#55]
Hi! 

This is my first time posting on github so hopefully this is the right place to put it.

The bot has stopped working entirely for me and does not respond to any commands. (both android and pc)  Am I the only one? 

No screenshots because it's doing... nothing

**Comment by seveneightn9ne** [comment]
Should be back up now, just had to restart the server

**Comment by CodedbyRed** [comment]
Thank you so much!

**Comment by CodedbyRed** [comment]
Seems to be down again, I'm getting no responses from any commands

**Comment by seveneightn9ne** [comment]
It's back

**Comment by CodedbyRed** [comment]
Thank you!
a reminder I had scheduled for the 19th got in this morning (in case that's useful)

**Comment by pdaengeli** [comment]
The bot is not functional since Dec 31st, likely related to the expiration of the build-in certificate (see recent issues at https://github.com/keybase/client/issues / https://github.com/keybase/keybase-issues/issues). In the meantime, updates for most platforms are out (v6.2.4/v6.3.0).

Maybe an update and restart is needed, thanks.

Edit: all good now (05.01.2024, 2:30 PM CET)
